# Generated by Django 5.1.2 on 2024-10-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language_code',
            field=models.CharField(blank=True, choices=[('fr', 'French'), ('en', 'English')], default='', max_length=7, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='language_code',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], max_length=7, verbose_name='Language'),
        ),
    ]
