# Generated by Django 5.1.2 on 2024-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_company_massmail_alter_contact_massmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(help_text='Use comma to separate Emails.', max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(help_text='Use comma to separate Emails.', max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(help_text='Use comma to separate Emails.', max_length=200, null=True, verbose_name='Email'),
        ),
    ]
