# Generated by Django 5.1.2 on 2024-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_company_email_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, default='', help_text='Use comma to separate Emails.', max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, default='', help_text='Use comma to separate Emails.', max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, default='', help_text='Use comma to separate Emails.', max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
    ]
