# Generated by Django 5.1.2 on 2024-10-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='crm.clienttype', verbose_name='Type of company'),
        ),
    ]
