# Generated by Django 5.1.2 on 2024-10-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.clienttype', verbose_name='Type of company'),
        ),
    ]
