# Generated by Django 5.1.2 on 2024-10-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='crm.company', verbose_name='Company of contact'),
        ),
        migrations.AlterField(
            model_name='request',
            name='company_name',
            field=models.CharField(default='', max_length=200, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='products',
            field=models.ManyToManyField(default='', to='crm.product', verbose_name='Products'),
        ),
    ]
