# Generated by Django 5.1.2 on 2024-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_request_company_alter_request_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Company email'),
        ),
    ]
